# Generated by Django 5.1.3 on 2024-12-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('sofa', 'Sofa'), ('recliner', 'Recliner'), ('nightstand', 'Nightstand'), ('dresser', 'Dresser'), ('dining', 'Dining Table'), ('desk', 'Desk'), ('coffee_table', 'Coffee Table'), ('bed', 'Bed'), ('armchair', 'Armchair')], max_length=20)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
